  include "../spelunk-constants.asm"
  org #0000
spelunk_ingame_song:
  db 7,184
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 0, 254
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 1
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db 10, 0
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 0, 214
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db 10, 0
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 0, 226
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db 10, 0
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 13
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db 10, 0
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
spelunk_ingame_song_loop:
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 0, 254
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 0, 214
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 0, 226
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 13
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 0, 254
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 64
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 1
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 1
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 1
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 1
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 13
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 1, 197
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 2
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3, 2, 27
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 1, 197
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3, 2, 27
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 1, 197
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3, 2, 27
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 46
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 1, 197
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3, 2, 93
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 13
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 1, 197
  db MUSIC_CMD_PLAY_INSTRUMENT_CH3, 2, 27
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_REPEAT, 2
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 3, 249
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 172
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 1, 252
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 172
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 3, 249
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 3, 249
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 172
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 1, 252
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 172
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 3, 249
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 6, 174
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 3, 87
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 172
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 1, 172
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 172
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 3, 87
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 6, 174
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 3, 87
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 172
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 1, 172
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 172
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 3, 87
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 27
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 20
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 27
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 3, 138
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 197
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 1, 197
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 197
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 27
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 3, 138
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 27
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 20
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 27
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 3, 138
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 197
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 1, 197
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 197
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 27
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 3, 138
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 27
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 27
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 53
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 197
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 2, 27
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 197
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 27
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 53
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 27
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 27
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 53
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 197
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 2, 27
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 197
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 27
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 53
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 3, 249
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 172
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 1, 252
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 172
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 3, 249
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 3, 249
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 172
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 1, 252
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 172
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 3, 249
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 2
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 129
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 1
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 172
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 64
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 2, 129
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 172
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 1
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 129
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 2
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 129
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 1
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 172
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 64
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 2, 129
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 172
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 1
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 129
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 172
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 2, 167
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 172
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 172
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 2, 167
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 172
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 27
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 27
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 53
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 197
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 2, 27
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 197
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 27
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 53
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 27
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 107
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 27
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 53
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 197
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 2, 27
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 197
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 27
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 53
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_END_REPEAT
  db MUSIC_CMD_GOTO
  dw (spelunk_ingame_song_loop - spelunk_ingame_song)
