  include "../spelunk-constants.asm"
  org #0000
spelunk_ingame2_song:
  db 7,184
spelunk_ingame2_song_loop:
  db 8, 0
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 1
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db 8, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 235
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 117
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 235
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 117
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 235
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 117
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 235
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 117
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db 8, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 20
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 3, 138
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 20
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 3, 138
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 20
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 3, 138
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 20
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 3, 138
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db 8, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 197
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 125
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 29
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 125
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 197
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 125
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 235
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 117
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 235
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 117
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_SQUARE_WAVE, 0
  db 8, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 235
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 117
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 235
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 117
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 197
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 235
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 197
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 117
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 125
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 197
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 235
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 59
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 117
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 167
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_SQUARE_WAVE, 0
  db 8, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 2, 59
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 235
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 117
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 235
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 117
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 252
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 197
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 20
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 125
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 3, 138
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 7, 20
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 197
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 3, 138
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_SQUARE_WAVE, 0
  db 8, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db 8, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 235
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 117
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 235
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 117
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 235
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 117
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 235
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 117
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db 8, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 9, 115
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 185
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 9, 115
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 185
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 9, 115
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 185
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 9, 115
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 185
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db 8, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 11, 231
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 244
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 11, 231
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 244
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 11, 231
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 244
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 11, 231
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 244
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 29
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 46
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 125
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 29
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 46
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 125
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 235
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 29
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 117
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 46
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 235
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 125
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 117
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 235
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 29
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 117
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 46
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 8, 235
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 125
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 117
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 9, 115
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 29
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 185
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 46
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 9, 115
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 125
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 185
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 9, 115
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 29
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 185
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 46
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 9, 115
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 125
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 4, 185
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 1, 83
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_SQUARE_WAVE, 0
  db 8, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 10, 155
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH2, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_GOTO
  dw (spelunk_ingame2_song_loop - spelunk_ingame2_song)
