SFX_boulder_pushed: equ 12DH
SFX_bullet_bounce: equ 1FCH
SFX_door_open: equ 12DH
SFX_end_ptr: equ 330H
SFX_enemy_kill: equ 2A3H
SFX_explosion: equ 209H
SFX_fire_arrow: equ 1A2H
SFX_fire_phaser: equ 1C5H
SFX_hit_deflected: equ 26CH
SFX_hit_enemy: equ 24AH
SFX_item_pickup: equ 0B7H
SFX_jump: equ 48H
SFX_open_hi_hat: equ 2FBH
SFX_pedal_hi_hat: equ 31AH
SFX_playerhit: equ 26H
SFX_start_ptr: equ 0H
SFX_sword_swing: equ 0FAH
SFX_timer: equ 2ECH
SFX_watersplash: equ 64H
SFX_watersplash_soft: equ 7AH
SFX_weapon_switch: equ 0H
