  include "../spelunk-constants.asm"
  org #0000
spelunk_intro_song:
  db 7,184
spelunk_intro_song_loop:
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_SQUARE_WAVE, 0
  db 8, 0
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 6, 174
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_SQUARE_WAVE, 0
  db 8, 0
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 6, 174
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 5, 158
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 5, 77
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 3, 249
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 5, 77
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 3, 249
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 3, 249
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 4, 53
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 4, 53
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 4, 117
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 4, 117
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 4, 185
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 4, 185
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 5, 1
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 5, 244
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 5, 158
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 5, 77
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_SQUARE_WAVE, 0
  db 8, 0
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_SQUARE_WAVE, 0
  db 8, 0
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 6, 174
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_SQUARE_WAVE, 0
  db 8, 0
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_PIANO, 0
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 6, 174
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 5, 158
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 5, 77
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 3, 249
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 5, 77
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 3, 249
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 3, 249
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 4, 53
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 4, 53
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 4, 117
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 4, 117
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 4, 185
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 4, 185
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 4, 185
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 5, 77
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 6, 174
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_INSTRUMENT_CH1, 7, 242
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SET_INSTRUMENT, MUSIC_INSTRUMENT_SQUARE_WAVE, 0
  db 8, 0
  db MUSIC_CMD_PLAY_SFX, SFX_PEDAL_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_PLAY_SFX, SFX_OPEN_HIHAT
  db MUSIC_CMD_SKIP
  db MUSIC_CMD_GOTO
  dw (spelunk_intro_song_loop - spelunk_intro_song)
